language: node_js
cache:
  directories:
    - .yarn-cache
    - node_modules

before_script:
  - set -e
  - yarn install --frozen-lockfile --cache-folder .yarn-cache
  - export UPDATES_JSON=$(mktemp)
  - export OPTIMIZED_MEDIA_DIR=$(mktemp -d)
script:
  - yarn test
  - ./generate-json > $UPDATES_JSON
  - ./optimize-media $OPTIMIZED_MEDIA_DIR
  - curl -sL scripts.piet.me/ci/setup-git | bash
  - git checkout --force gh-pages
  - cp -v $UPDATES_JSON updates.json
  - rm -vr media/
  - cp -vr $OPTIMIZED_MEDIA_DIR media/
  - git add updates.json
  - git add media
  - git commit -m 'update json and media [skip ci]' || true
  - git push

env:
  global:
    secure: Ubf5euS84P29yjA8oeIIFna0fcGK0KPAklXr+IpXYu1ymbldo1WBWpWiMXeYh5KgqrSTfyuEC5VKpCx+kRV3dcOq0FqQFBvyv7BdL90ebR48wPNdQXo0Tus/r5TgBq5dicqe7BCE9cWLRTsvKdp5Ta2ja6oZV4lgYCHvz3I0OrmZXJtCTI3lg/LP9cBT6UzkwQbgZgEG8h+qhIRMMH9u1mZBGyHl+xKq9sg+ifCEdo8zjxw8WjRTrpHhujsJrov5pRF8B5j/Tx4Ius/ENAMhz66G7DnRnZlS3scE0jUCLfk8SiYq3yyG1XsbFeH4C+j2+OhcXebYr+bvAOFYyP7yttDHVorcNqN0w5Fh2L12NyipKkaw0K01kb4MHO2Azf521A4f7D84mpFx8EOLUkSqFD7orY2nGbPxdoQ0M/K1CTUm97Wg+uGT2igrA7UMdUJKy9T6Jb6tCVFjEe1+yun97UGh9H4oNm3pHym+are5vHKSD5sTwrAOxaTIhd9UC+jdcpOpodKAICMzBimbVwfACVQuWfnOEgVtrJnoYvTRu96yFd02AMYNAossKJrosOuVCV0MoUb6v06EQiHLz0uQ9l30098+TZ57mgKkMltZKio1U/qzwtMqyumxR3kRPvp6QgSa0yHTLHuUnOVJGsNpYPN0GldaqN9kZtT5JaouNAU=
