#!/usr/bin/env node
// parses markdown files and generates json file listing

const fs = require("fs");
const UPDATE_FILES_REGEX = /\d{4}-\d{2}-\d{2}-.*\.md$/;
const processFiles = require("./lib/process-files");

const files = fs
  .readdirSync(".")
  .filter(file => UPDATE_FILES_REGEX.test(file))
  .map(file => fs.readFileSync(file));

const processor = processFiles({
  mediaPrefix: "https://pietvanzoen.github.io/updates"
});

// eslint-disable-next-line
console.log(JSON.stringify({ updates: processor(files) }));
