#!/usr/bin/env node
// parses markdown files and generates json file listing

const fs = require("fs");
const processFiles = require("./lib/process-files");

const files = fs
  .readdirSync(".")
  .filter(file => /\d{4}-\d{2}-\d{2}-.*\.md$/.test(file));

processFiles({
  mediaPrefix: "https://pietvanzoen.github.io/updates"
})(files)
  .then(updates => {
    console.log(JSON.stringify({ updates }));
  })
  .catch(err => {
    console.error(err);
  });
