#!/usr/bin/env node

const { readdirSync, readFileSync, writeFileSync } = require("fs");
const { join, basename } = require("path");
const optimizeMedia = require("./lib/optimize-media");

const IN_DIR = "./media";
const OUT_DIR = process.argv[2];

if (!OUT_DIR) throw new TypeError("Out directory is required");

Promise.all(
  readdirSync(IN_DIR).map(filepath => {
    const buffer = readFileSync(join(IN_DIR, filepath));
    const optimizedPath = join(OUT_DIR, basename(filepath));
    return optimizeMedia(buffer)
      .then(buffer => writeFileSync(optimizedPath, buffer))
      .then(() => console.log(`Wrote ${optimizedPath}`))
      .catch(err => {
        console.error(`Failed to optimize ${filepath}`, err);
      });
  })
).then(files => {
  console.error(`${files.length} files optimized`);
});
