#!/bin/bash
set -ex

curl -v -H "Accept: application/vnd.github.everest-preview+json" \
  -H "Authorization: token $GITHUB_TOKEN" \
  --request POST \
  --data '{"event_type": "trigger-build"}' \
  https://api.github.com/repos/pietvanzoen/pietvanzoen.com/dispatches
