name: CI

on: [push]

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Piet.me Build
        run: |
          curl -X POST https://api.github.com/repos/pietvanzoen/piet.me/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "trigger-build"}'
